apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amine7536/akpe-backend-1.git
    targetRevision: main
    path: k8s
    helm:
      parameters:
        - name: image.tag
          value: "6be0ec641b91e6e7ec754a84b6a58d5ad24bc1cd"
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
