apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amine7536/akpe-front.git
    targetRevision: main
    path: k8s
    helm:
      parameters:
        - name: image.tag
          value: "720db837386a87d489e980cf38e26dd5b5b6528d"
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
