apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amine7536/akpe-front.git
    targetRevision: main
    path: k8s
    helm:
      parameters:
        - name: image.tag
          value: "435d3b7a32d8294968fb61951762ca25558f2883"
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
