apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Preview environment: {{ .Release.Name }}"
  sourceRepos:
    - "https://github.com/amine7536/akpe-*"
    - "https://charts.bitnami.com/bitnami"
  destinations:
    - namespace: {{ .Release.Name }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
